apiVersion: v1
kind: Service
metadata:
  name: exchange-service
spec:
  selector:
    app: exchange-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: NodePort
